version: '2'
services:
  default:
    image: troubleticket
    container_name: troubleticket
    build:
      context: ./docker
      dockerfile: Dockerfile
    expose:
     - "80"
    tty: true
    environment:
      TERM: xterm
    volumes:
      - ./:/var/www/html
#      - /mnt/dados:/mnt/dados
networks:
  default:
    external:
      name: mynet
