Servicos\FinanceiroBundle\Entity\Ar:
    type: entity
    table: financeiro.ar
    indexes:
        fk_ar_rangear1_idx:
            columns:
                - rangar_codigoid
    id:
        arCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: ar_codigoid
            generator:
                strategy: IDENTITY
    fields:
        arNumero:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: ar_numero
    manyToOne:
        rangarCodigoid:
            targetEntity: Rangear
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                rangar_codigoid:
                    referencedColumnName: rangar_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
