Servicos\FinanceiroBundle\Entity\Atributovalor:
    type: entity
    table: financeiro.atributovalor
    repositoryClass: Servicos\FinanceiroBundle\Repository\AtributovalorRepository
    indexes:
        fk_atributovalor_atributo1_idx:
            columns:
                - atri_codigoid
    id:
        atrivaloCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: atrivalo_codigoid
            generator:
                strategy: IDENTITY
    fields:
        atrivaloValor:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: atrivalo_valor
        mask:
            type: string
            nullable: true
            length: 45
            fixed: false
    manyToOne:
        atriCodigoid:
            targetEntity: Atributo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                atri_codigoid:
                    referencedColumnName: atri_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
