Servicos\FinanceiroBundle\Entity\Contratoproposta:
    type: entity
    table: financeiro.contratoproposta
    repositoryClass: Servicos\FinanceiroBundle\Repository\ContratoPropostaRepository
    uniqueConstraints:
        idcontrato_proposta_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idproposal:
            type: integer
            nullable: false
            unsigned: false
        idcontrato:
            type: integer
            nullable: false
            unsigned: false
    lifecycleCallbacks: {  }
