Servicos\FinanceiroBundle\Entity\Envio:
    type: entity
    table: financeiro.envio
    id:
        enviCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: envi_codigoid
            generator:
                strategy: IDENTITY
    fields:
        enviNome:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: envi_nome
    lifecycleCallbacks: {  }
