Servicos\FinanceiroBundle\Entity\Logging:
    type: entity
    table: financeiro.logging
    indexes:
        fk_logging_tipologging1_idx:
            columns:
                - tipologg_codigoid
    id:
        loggCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: logg_codigoid
            generator:
                strategy: IDENTITY
    fields:
        usuaCodigoid:
            type: integer
            nullable: true
            unsigned: false
            column: usua_codigoid
        loggDatainc:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: logg_datainc
        loggIp:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: logg_ip
        loggOldendata:
            type: text
            nullable: true
            length: 65535
            fixed: false
            column: logg_oldendata
        loggDatabase:
            type: string
            nullable: true
            length: 25
            fixed: false
            column: logg_database
        loggTable:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: logg_table
        loggTableid:
            type: integer
            nullable: true
            unsigned: false
            column: logg_tableid
    manyToOne:
        tipologgCodigoid:
            targetEntity: Tipologging
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipologg_codigoid:
                    referencedColumnName: tipologg_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
