Servicos\FinanceiroBundle\Entity\Sla:
    type: entity
    table: financeiro.sla
    indexes:
        fk_sla_sla1_idx:
            columns:
                - sla_proximocodigoid
    id:
        slaCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: sla_codigoid
            generator:
                strategy: IDENTITY
    fields:
        slaNome:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: sla_nome
        slaDatainc:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: sla_datainc
        slaDatafim:
            type: datetime
            nullable: true
            column: sla_datafim
        slaDisponibilidade:
            type: decimal
            nullable: false
            precision: 5
            scale: 2
            column: sla_disponibilidade
    oneToMany:
        contrato:
            targetEntity: Contrato
            cascade: {  }
            mappedBy: slaCodigoid
        slanivel:
            targetEntity: Slanivel
            cascade: {  }
            mappedBy: slaCodigoid
    manyToOne:
        slaProximocodigoid:
            targetEntity: Sla
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sla_proximocodigoid:
                    referencedColumnName: sla_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
