Servicos\FinanceiroBundle\Entity\Slanivel:
    type: entity
    table: financeiro.slanivel
    indexes:
        fk_slanivel_nivel1_idx:
            columns:
                - nive_codigoid
        fk_slanivel_sla1_idx:
            columns:
                - sla_codigoid
    id:
        slaniveCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: slanive_codigoid
            generator:
                strategy: IDENTITY
    fields:
        slaniveRespostacomercial:
            type: integer
            nullable: false
            unsigned: false
            column: slanive_respostacomercial
        slaniveResolucaocomercial:
            type: integer
            nullable: false
            unsigned: false
            column: slanive_resolucaocomercial
        slaniveResolucaoextra:
            type: integer
            nullable: false
            unsigned: false
            column: slanive_resolucaoextra
        slaniveRespostaextra:
            type: integer
            nullable: false
            unsigned: false
            column: slanive_respostaextra
    manyToOne:
        niveCodigoid:
            targetEntity: Nivel
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                nive_codigoid:
                    referencedColumnName: nive_codigoid
            orphanRemoval: false
        slaCodigoid:
            targetEntity: Sla
            cascade: {  }
            mappedBy: null
            inversedBy: slanivel
            joinColumns:
                sla_codigoid:
                    referencedColumnName: sla_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
