services:
    
    SSOBundle.client:
        class: SSOBundle\Service\SSOClientService
        arguments: ['@service_container']

    SSOBundle.auth:
        class: SSOBundle\Service\SSOAuthService
        arguments: ['@service_container']
        
    SSOBundle.authExceptions:
        class: SSOBundle\Service\SSOAuthExceptionService
        arguments: ['@service_container']

    SSOBundle.requestListener:
        class: SSOBundle\EventListener\SSOAuthEventListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 2 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 9999999 }
        