<?php

namespace Servicos\LumaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PopRepository extends EntityRepository
{
	public function listar($campos = 'p', $where = array(), $order = null, $limit = null, $offset = null){
		$query = $this->_em->createQueryBuilder();

		$query->select(implode(", ", $campos));
		$query->from("ServicosLumaBundle:Pop", "p");
		$query->innerJoin("p.idEstruturaFisica", "pef");
		$query->innerJoin("p.idPopLocalizacao", "pl");
		$query->innerJoin("p.idConcessionaria", "pc");

		foreach ($where as $key => $condicao) {
			if(is_null($condicao)){
				$query->andWhere($query->expr()->isNull($key));
			} else if(is_array($condicao)){
				$query->andWhere($query->expr()->in($key, $condicao));
			} else{
				$query->andWhere($query->expr()->eq($key, $condicao));
			}
		}

		if($limit){
			$query->setMaxResults($limit);
		}

		if($offset){
			$query->setFirstResult($offset);
		}

		if($order and is_array($order)){
			$query->orderBy($order['sort'], $order['order']);
		}

		return $query->getQuery()->execute();
	}
}