<?php

namespace Servicos\LumaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRepository extends EntityRepository
{
	private $arrayColumnTipo = array(
		'tipo.tipoCodigoid',
		'tipo.tipoNome',
		'tipo.tipoTipo'
	);
	
	public function getColumnsTipo(){
		return $this->arrayColumnTipo;
	}
	
	public function getTipo($tipoCodigoid){
		try{
			$column = implode(',', $this->arrayColumnTipo);
			$arrayWhere = array(
				array('tipo.tipoCodigoid', '=', (integer)$tipoCodigoid)
			);
			return $this->findGeral(0, 0, $arrayWhere, array('tipo.tipoCodigoid' => 'ASC'), array('tipo.tipoCodigoid'), $column);
		}catch(Exception $e){
		}
	}

	public function countTipo($arrayWhere = array(), $groupBy = array()){
		try{
			$column = 'COUNT(tipo.tipoCodigoid) AS total';
			return $this->findGeral(0, 0, $arrayWhere, array(), $groupBy, $column);
		}catch (\Exception $ex){
			throw $ex;
		}
	}

	public function listTipo($offset = 0, $limit = 50, $arrayWhere = array(), $orderBy = array('tipo.tipoCodigoid' => 'ASC'), $groupBy = array('tipo.tipoCodigoid')){
		try{
			$column = implode(',', $this->arrayColumnTipo);
			return $this->findGeral($offset, $limit, $arrayWhere, $orderBy, $groupBy, $column);
		}catch (\Exception $ex){
			throw $ex;
		}
	}
	
	private function findGeral($offset = 0, $limit = 100, $arrayWhere = array(), $orderBy = array('tipo.tipoCodigoid' => 'ASC'), $groupBy = array(), $column = 'cont.contCodigoid')
	{
		try {
			$query = $this->_em->createQueryBuilder();
			$query->select($column)
			->from("ServicosLumaBundle:Tipo", "tipo")
			//->leftJoin("line.billing", "bill", 'WITH', 'TO_CHAR(bill.billTimeStart, \'YYYY-MM\') = montpaym.usePeriod')
			;

			if (count($arrayWhere) > 0) {
				foreach ($arrayWhere as $where) {
					if (count($where) < 3){
						throw new \RuntimeException('Invalid argument');
					}
					$bind_parameter = 'a'.rand(0, 999999);
					if(strtoupper(trim($where[1])) == 'IS NOT'){
						$query->andWhere($where[0].' IS NOT '.$where[2]);
					}elseif (strtoupper(trim($where[1])) == 'IS') {
						$query->andWhere($where[0].' IS '.$where[2]);
					}elseif (strtoupper(trim($where[1])) == 'IN' && (count($where[2]) || count(explode(',', $where[2])))){
						if(!is_array($where[2])){
							$where[2] = explode(',', $where[2]);
						}
						$query->andWhere(trim($where[0]).' '.trim($where[1]).' (:'.$bind_parameter.')');
						$values = array_values($where[2]);
	
						if(is_integer($values[0])){
							$query->setParameter(':'.$bind_parameter, array_values($where[2]), \Doctrine\DBAL\Connection::PARAM_INT_ARRAY);
						}else{
							$query->setParameter(':'.$bind_parameter, array_values($where[2]), \Doctrine\DBAL\Connection::PARAM_STR_ARRAY);
						}
	
					}elseif(strtoupper(trim($where[1])) == 'NOT IN' && (count($where[2]) || count(explode(',', $where[2])))){
						if(!is_array($where[2])){
							$where[2] = explode(',', $where[2]);
						}
						$query->andWhere(trim($where[0]).' '.trim($where[1]).' (:'.$bind_parameter.')');
						$values = array_values($where[2]);
	
						if(is_integer($values[0])){
							$query->setParameter(':'.$bind_parameter, array_values($where[2]), \Doctrine\DBAL\Connection::PARAM_INT_ARRAY);
						}else{
							$query->setParameter(':'.$bind_parameter, array_values($where[2]), \Doctrine\DBAL\Connection::PARAM_STR_ARRAY);
						}
					}else{
						$query->andWhere($where[0].' '.$where[1].' :'.$bind_parameter);
						$query->setParameter($bind_parameter, $where[2]);
					}
				}
			}
	
			if(is_array($groupBy) && count($groupBy)){
				foreach($groupBy as $group){
					$query->addGroupBy($group);
				}
			}
	
			if(is_array($orderBy) && count($orderBy)){
				foreach($orderBy as $order => $sort){
					$query->addOrderBy($order, $sort);
				}
			}
	
			if($offset){
				$query->setFirstResult($offset);
			}
				
			if($limit){
				$query->setMaxResults($limit);
			}
				
			return $query->getQuery()->execute();
	
		}catch (\Exception $e){
			throw new \Exception($e->getMessage(), $e->getCode());
		}
	}
}