imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: '@SSOBundle/Resources/config/services.yml'}
    - { resource: '@TroubleticketBundle/Resources/config/parameters.yml' }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
#        storage_id: session.storage.php_bridge
#        handler_id: ~
        save_path: /var/lib/php/session

    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   troubleticket
        types:
            text_array: "Doctrine\\DBAL\\PostgresTypes\\TextArrayType"
            int_array: "Doctrine\\DBAL\\PostgresTypes\\IntArrayType"
            tsvector: "Doctrine\\DBAL\\PostgresTypes\\TsvectorType"
            tsquery: "Doctrine\\DBAL\\PostgresTypes\\TsqueryType"
            xml: "Doctrine\\DBAL\\PostgresTypes\\XmlType"
            inet: "Doctrine\\DBAL\\PostgresTypes\\InetType"
        connections:
            troubleticket:
                dbname:   "%troub.name%"
                host:     "%troub.host%"
                port:     "%troub.port%"
                user:     "%troub.user%"
                password: "%troub.password%"
                driver:   "%troub.driver%"
                charset:  UTF8
            luma:
                dbname:   "%luma.name%"
                host:     "%luma.host%"
                port:     "%luma.port%"
                user:     "%luma.user%"
                password: "%luma.password%"
                driver:   "%luma.driver%"
                charset:  UTF8
                mapping_types:
                    enum: string
            default:
                driver:   "%gcdb.driver%"
                host:     "%gcdb.host%"
                port:     "%gcdb.port%"
                dbname:   "%gcdb.name%"
                user:     "%gcdb.user%"
                password: "%gcdb.password%"
                charset:  UTF8
                mapping_types:
                    enum: string
            financeiro:
                driver:   "%fina.driver%"
                host:     "%fina.host%"
                port:     "%fina.port%"
                dbname:   "%fina.name%"
                user:     "%fina.user%"
                password: "%fina.password%"
                charset:  UTF8
                mapping_types:
                    enum: string
            rh:
                dbname:   "%rh.name%"
                host:     "%rh.host%"
                port:     "%rh.port%"
                user:     "%rh.user%"
                password: "%rh.password%"
                driver:   "%rh.driver%"
                charset:  UTF8
                mapping_types:
                    enum: string
    orm:
        default_entity_manager:  troubleticket
        auto_generate_proxy_classes:  true
        entity_managers:
            troubleticket:
                connection: troubleticket
                mappings:
                    TroubleticketBundle:
                        mapping:              true
                        type:                 annotation
                        prefix:               TroubleticketBundle\Entity
                dql:
                    string_functions:
                        cast: TroubleticketBundle\Query\Postgres\Cast
            luma:
                connection: luma
                mappings:
                    ServicosLumaBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Resources/config/doctrine
                        prefix:               Servicos\LumaBundle\Entity
            financeiro:
                connection: financeiro
                mappings:
                    ServicosFinanceiroBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Resources/config/doctrine
                        prefix:               Servicos\FinanceiroBundle\Entity
                    ServicosGcdbBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Resources/config/doctrine
                        prefix:               Servicos\GcdbBundle\Entity
                    ServicosLumaBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Resources/config/doctrine
                        prefix:               Servicos\LumaBundle\Entity
                dql:
                    string_functions:
                        GROUP_CONCAT: Servicos\FinanceiroBundle\Query\Mysql\GroupConcat
                        IF: Servicos\FinanceiroBundle\Query\Mysql\IfElse
                        LPAD: Servicos\FinanceiroBundle\Query\Mysql\Lpad
                        REPLACE: Servicos\FinanceiroBundle\Query\Mysql\Replace
                    datetime_functions:
                        DATE_FORMAT: Servicos\FinanceiroBundle\Query\Mysql\DateFormat
            default:
                connection: default
                mappings:
                    ServicosGcdbBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Resources/config/doctrine
                        prefix:               Servicos\GcdbBundle\Entity
                dql:
                    string_functions:
                        GROUP_CONCAT: Servicos\GcdbBundle\Query\Mysql\GroupConcat
                        IF: Servicos\GcdbBundle\Query\Mysql\IfElse
                        LPAD: Servicos\GcdbBundle\Query\Mysql\Lpad
                        REPLACE: Servicos\GcdbBundle\Query\Mysql\Replace
                        CONCAT_WS: Servicos\GcdbBundle\Query\Mysql\ConcatWs

            rh:
                connection: rh
                mappings:
                    ServicosRhBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Resources/config/doctrine
                        prefix:               Servicos\RhBundle\Entity
                    ServicosGcdbBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Resources/config/doctrine
                        prefix:               Servicos\GcdbBundle\Entity
                    ServicosLumaBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Resources/config/doctrine
                        prefix:               Servicos\LumaBundle\Entity
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
troubleticket:
    sistech_api:
        url: 'http://dev.vogeltelecom.com:5001/vogel/web/rest/'
        limit: 100
    overdue_limit: 4
    overdue_last_update: 30
    user_exception:
        - 4819
    toa:
        url: 'https://api.etadirect.com/rest/ofscCore/v1/activities?COMPANY=vogeltelecom2.test'
        authversion: "2.0"
        access_token: "c23fcec38354a3e9ac31bc70c3d83a9d6c3f2eb3"
        url_corp: "http://hlg.vogeltelecom.com:6015/"
        user_toa_id: 423
        toa_api: '192.168.43.29:8000/app_dev.php/toa/out/subcasos/activities'
knp_snappy:
    pdf:
        enabled: true
        binary: "%kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64"

