<?php

namespace Servicos\GcdbBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DevicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevicesRepository extends EntityRepository
{
    public function listDeviceIDs($cid = null){
        try{
            $query = $this->_em->createQueryBuilder();
            $query->select('devi.deviceID')
            ->from("ServicosGcdbBundle:Devices", "devi")
            ->andWhere('devi.active = 1')
            ->andWhere('devi.customer ='.$cid);
        }catch (\Exception $ex){
            throw $ex;
        }

        return $query->getQuery()->getArrayResult();
    }
}
