<?php

namespace Servicos\RhBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RhCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhCargoRepository extends EntityRepository
{
}
