Servicos\LumaBundle\Entity\Finalidade:
    type: entity
    table: luma.finalidade
    id:
        finaCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: fina_codigoid
            generator:
                strategy: IDENTITY
    fields:
        finaNome:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: fina_nome
        finaDescricao:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: fina_descricao
    lifecycleCallbacks: {  }
