Servicos\LumaBundle\Entity\Matrizmovimentacoes:
    type: entity
    table: luma.matrizmovimentacoes
    indexes:
        fk_matrizmovimentacoes_tipo1_idx:
            columns:
                - tipo_decodigoid
        fk_matrizmovimentacoes_tipo2_idx:
            columns:
                - tipo_paracodigoid
        fk_matrizmovimentacoes_finalidade1_idx:
            columns:
                - fina_codigoid
    id:
        matrmoviCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: matrmovi_codigoid
            generator:
                strategy: IDENTITY
    fields:
        matrmoviInterna:
            type: boolean
            nullable: false
            column: matrmovi_interna
        matrmoviExterna:
            type: boolean
            nullable: false
            column: matrmovi_externa
    manyToOne:
        finaCodigoid:
            targetEntity: Finalidade
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                fina_codigoid:
                    referencedColumnName: fina_codigoid
            orphanRemoval: false
        tipoDecodigoid:
            targetEntity: Tipo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_decodigoid:
                    referencedColumnName: tipo_codigoid
            orphanRemoval: false
        tipoParacodigoid:
            targetEntity: Tipo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_paracodigoid:
                    referencedColumnName: tipo_codigoid
            orphanRemoval: false
    lifecycleCallbacks: {  }
