Servicos\LumaBundle\Entity\Medida:
    type: entity
    table: luma.medida
    id:
        mediCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: medi_codigoid
            generator:
                strategy: IDENTITY
    fields:
        mediNome:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: medi_nome
        mediSigla:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: medi_sigla
    lifecycleCallbacks: {  }
