Servicos\LumaBundle\Entity\Popbateria:
    type: entity
    table: luma.popbateria
    indexes:
        id_pop:
            columns:
                - id_pop
    id:
        idBaterias:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_baterias
            generator:
                strategy: IDENTITY
    fields:
        capacidade:
            type: integer
            nullable: true
            unsigned: false
        quantidade:
            type: integer
            nullable: true
            unsigned: false
        modelo:
            type: string
            nullable: true
            length: 200
            fixed: false
        dataInicio:
            type: datetime
            nullable: true
            column: data_inicio
        dataFim:
            type: datetime
            nullable: true
            column: data_fim
        usuario:
            type: string
            nullable: true
            length: 80
            fixed: false
        erro:
            type: string
            nullable: true
            length: 5000
            fixed: false
        tipo:
            type: string
            nullable: true
            length: 50
            fixed: false
        movimentacao:
            type: integer
            nullable: true
            unsigned: false
    manyToOne:
        idPop:
            targetEntity: Pop
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_pop:
                    referencedColumnName: id_pop
            orphanRemoval: false
    lifecycleCallbacks: {  }
