Servicos\LumaBundle\Entity\Poptiporf:
    type: entity
    table: luma.poptiporf
    id:
        idTipoRf:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_tipo_rf
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 100
            fixed: false
    lifecycleCallbacks: {  }
