Servicos\LumaBundle\Entity\TempUnidade:
    type: entity
    table: luma._temp_unidade
    id:
        unidCodigoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: unid_codigoid
            generator:
                strategy: IDENTITY
    fields:
        tipoNome:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: tipo_nome
        unidNome:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: unid_nome
    lifecycleCallbacks: {  }
