Servicos\LumaBundle\Entity\ViaturaModelo:
    type: entity
    table: luma.viatura_modelo
    indexes:
        fk_modelo_marca_viatura1_idx:
            columns:
                - viat_marcaid
    id:
        viatModeloid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: viat_modeloid
            generator:
                strategy: IDENTITY
    fields:
        modelCadUsuarioid:
            type: integer
            nullable: true
            unsigned: false
            column: model_cad_usuarioid
        modelCnh:
            type: string
            nullable: true
            length: 5
            fixed: false
            column: model_cnh
        modelo:
            type: string
            nullable: true
            length: 45
            fixed: false
        modelDatainc:
            type: datetime
            nullable: true
            default: CURRENT_TIMESTAMP
            column: model_datainc
        modelImagem:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: model_imagem
        modelAtivo:
            type: boolean
            nullable: true
            default: '1'
            column: model_ativo
    manyToOne:
        viatMarcaid:
            targetEntity: ViaturaMarca
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                viat_marcaid:
                    referencedColumnName: viat_marcaid
            orphanRemoval: false
    lifecycleCallbacks: {  }
