Servicos\LumaBundle\Entity\ViaturaAlienacao:
    type: entity
    table: luma.viatura_alienacao
    indexes:
        fk_viatura_alienacao_viatura1_idx:
            columns:
                - viaturaid
    id:
        viaturaAlienacaoid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: viatura_alienacaoid
            generator:
                strategy: IDENTITY
    fields:
        alieUserAlienado:
            type: integer
            nullable: true
            unsigned: false
            column: alie_user_alienado
        alieCadUsuarioid:
            type: integer
            nullable: true
            unsigned: false
            column: alie_cad_usuarioid
        alieDatainc:
            type: datetime
            nullable: true
            default: CURRENT_TIMESTAMP
            column: alie_datainc
        alieDataPrevista:
            type: datetime
            nullable: true
            column: alie_data_prevista
        alieDataFinal:
            type: datetime
            nullable: true
            column: alie_data_final
        ativo:
            type: boolean
            nullable: true
            default: '1'
        observacao:
            type: string
            nullable: true
            length: 255
            fixed: false
    manyToOne:
        viaturaid:
            targetEntity: Viatura
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                viaturaid:
                    referencedColumnName: viaturaid
            orphanRemoval: false
    lifecycleCallbacks: {  }
