Servicos\RhBundle\Entity\DoctrineMigrationVersions:
    type: entity
    table: doctrine_migration_versions
    id:
        version:
            type: string
            nullable: false
            length: 14
            fixed: false
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
