Servicos\RhBundle\Entity\RhAdvertencia:
    type: entity
    table: rh.rh_advertencia
    id:
        idAdvertencia:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_advertencia
            generator:
                strategy: IDENTITY
    fields:
        descricao:
            type: string
            nullable: true
            length: 255
            fixed: false
        dataInc:
            type: date
            nullable: true
            column: data_inc
    lifecycleCallbacks: {  }
