Servicos\RhBundle\Entity\RhBeneficio:
    type: entity
    table: rh.rh_beneficio
    id:
        idBeneficio:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_beneficio
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 255
            fixed: false
        descricao:
            type: string
            nullable: true
            length: 255
            fixed: false
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        registrante:
            type: integer
            nullable: true
            unsigned: false
        cartaoLuma:
            type: boolean
            nullable: true
            column: cartao_luma
        ativo:
            type: boolean
            nullable: true
        registranteEdicao:
            type: integer
            nullable: true
            unsigned: false
            column: registrante_edicao
        dataEdicao:
            type: datetime
            nullable: true
            column: data_edicao
        motivoEdicao:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: motivo_edicao
    lifecycleCallbacks: {  }
