Servicos\RhBundle\Entity\RhCargo:
    type: entity
    repositoryClass: Servicos\RhBundle\Repository\RhCargoRepository
    table: rh.rh_cargo
    indexes:
        fk_rh_cargo_rh_tipo_cargo1_idx:
            columns:
                - id_tipo_cargo
        fk_rh_cargo_rh_grupo_material1_idx:
            columns:
                - id_cargo_material
    id:
        idCargo:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_cargo
            generator:
                strategy: IDENTITY
    fields:
        cargo:
            type: string
            nullable: false
            length: 255
            fixed: false
        descricao:
            type: string
            nullable: true
            length: 255
            fixed: false
        motivoEdicao:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: motivo_edicao
        registranteEdicao:
            type: integer
            nullable: true
            unsigned: false
            column: registrante_edicao
        dataEdicao:
            type: datetime
            nullable: true
            column: data_edicao
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        registrante:
            type: integer
            nullable: true
            unsigned: false
        nivel:
            type: string
            nullable: true
            length: 5
            fixed: false
        idGrupoSistech:
            type: integer
            nullable: true
            unsigned: false
            column: id_grupo_sistech
        crea:
            type: boolean
            nullable: true
        ativo:
            type: boolean
            nullable: true
    oneToMany:
        colaboradorCargo:
            targetEntity: RhColaboradorCargo
            mappedBy: idCargo
    manyToOne:
        idCargoMaterial:
            targetEntity: RhGrupoMaterial
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_cargo_material:
                    referencedColumnName: id_cargo_material
            orphanRemoval: false
        idTipoCargo:
            targetEntity: RhTipoCargo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_cargo:
                    referencedColumnName: id_tipo_cargo
            orphanRemoval: false
    manyToMany:
        rhDepartamentoDepartamento:
            targetEntity: RhDepartamento
            cascade: {  }
            mappedBy: rhCargoCargo
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
