Servicos\RhBundle\Entity\RhCargoOrdenado:
    type: entity
    table: rh.rh_cargo_ordenado
    indexes:
        fk_rh_cargo_ordenado_rh_cargo1_idx:
            columns:
                - id_cargo
    id:
        idCargoOrdenado:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_cargo_ordenado
            generator:
                strategy: IDENTITY
    fields:
        ordenadoCargo:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            column: ordenado_cargo
        periculosidade:
            type: float
            nullable: true
            precision: 10
            scale: 0
        insalubridade:
            type: float
            nullable: true
            precision: 10
            scale: 0
        registrante:
            type: integer
            nullable: true
            unsigned: false
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        dataEdicao:
            type: datetime
            nullable: true
            column: data_edicao
        registranteEdicao:
            type: integer
            nullable: true
            unsigned: false
            column: registrante_edicao
        motivoEdicao:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: motivo_edicao
        ativo:
            type: boolean
            nullable: true
    manyToOne:
        idCargo:
            targetEntity: RhCargo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_cargo:
                    referencedColumnName: id_cargo
            orphanRemoval: false
    lifecycleCallbacks: {  }
