Servicos\RhBundle\Entity\RhColaborador:
    type: entity
    repositoryClass: Servicos\RhBundle\Repository\RhColaboradorRepository
    table: rh.rh_colaborador
    indexes:
        fk_rh_colaborador_rh_tipo_colaborador1_idx:
            columns:
                - id_tipo_colaborador
        fk_rh_colaborador_rh_colaborador1_idx:
            columns:
                - id_colaborador_pai
        id_colaborador_anterior:
            columns:
                - id_colaborador_anterior
    id:
        idColaborador:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_colaborador
            generator:
                strategy: IDENTITY
    fields:
        idCadUserSistech:
            type: integer
            nullable: true
            unsigned: false
            column: id_cad_user_sistech
        idAltUsuarioSistech:
            type: integer
            nullable: true
            unsigned: false
            column: id_alt_usuario_sistech
        unidCodigoid:
            type: integer
            nullable: true
            unsigned: false
            column: unid_codigoid
        matricula:
            type: integer
            nullable: true
            unsigned: false
        fone:
            type: string
            nullable: true
            length: 45
            fixed: false
        endereco:
            type: string
            nullable: true
            length: 45
            fixed: false
        dataNascimento:
            type: datetime
            nullable: true
            column: data_nascimento
        localNascimento:
            type: integer
            nullable: true
            unsigned: false
            column: local_nascimento
        estadoCivil:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: estado_civil
        nome:
            type: string
            nullable: true
            length: 255
            fixed: false
        filiacaoProfissao:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: filiacao_profissao
        sexo:
            type: string
            nullable: true
            length: 1
            fixed: true
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        cpf:
            type: string
            nullable: true
            length: 45
            fixed: false
        registrante:
            type: integer
            nullable: true
            unsigned: false
        ativo:
            type: boolean
            nullable: true
            default: '0'
    oneToOne:
        cadUsers:
            targetEntity: \Servicos\GcdbBundle\Entity\CadUsers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_cad_user_sistech:
                    referencedColumnName: id
            orphanRemoval: false
        autUsuarios:
            targetEntity: \Servicos\GcdbBundle\Entity\AutUsuarios
            cascade:
                - persist
                - merge
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_alt_usuario_sistech:
                    referencedColumnName: id
            orphanRemoval: false
        unidade:
            targetEntity: \Servicos\LumaBundle\Entity\Unidade
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                unid_codigoid:
                    referencedColumnName: unid_codigoid
            orphanRemoval: false
    oneToMany:
        colaboradorCargo:
            targetEntity: RhColaboradorCargo
            mappedBy: idColaborador
        colaboradorDepartamento:
            targetEntity: RhColaboradorDepartamento
            mappedBy: idColaborador
            cascade:
                - persist
                - merge
                - remove
        colaboradorFilial:
            targetEntity: RhColaboradorFilial
            mappedBy: idColaborador

    manyToOne:
        idColaboradorPai:
            targetEntity: RhColaborador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_colaborador_pai:
                    referencedColumnName: id_colaborador
            orphanRemoval: false
        idTipoColaborador:
            targetEntity: RhTipoColaborador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_colaborador:
                    referencedColumnName: id_tipo_colaborador
            orphanRemoval: false
        idColaboradorAnterior:
            targetEntity: RhColaborador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_colaborador_anterior:
                    referencedColumnName: id_colaborador
            orphanRemoval: false
    lifecycleCallbacks: {  }
