Servicos\RhBundle\Entity\RhColaboradorBanco:
    type: entity
    table: rh.rh_colaborador_banco
    indexes:
        fk_rh_colaborador_banco_rh_colaborador1_idx:
            columns:
                - id_colaborador
        fk_rh_colaborador_banco_rh_conta_definicao1_idx:
            columns:
                - id_banco_definicao
        fk_rh_colaborador_banco_rh_banco_operacao1_idx:
            columns:
                - id_banco_operacao
    id:
        idColaboradorBanco:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_colaborador_banco
            generator:
                strategy: IDENTITY
    fields:
        idColaborador:
            type: integer
            nullable: false
            unsigned: false
            column: id_colaborador
        idBancoDefinicao:
            type: integer
            nullable: false
            unsigned: false
            column: id_banco_definicao
        idBancoOperacao:
            type: integer
            nullable: false
            unsigned: false
            column: id_banco_operacao
        agencia:
            type: string
            nullable: true
            length: 45
            fixed: false
        conta:
            type: string
            nullable: true
            length: 45
            fixed: false
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        dataEdicao:
            type: datetime
            nullable: true
            column: data_edicao
        registrante:
            type: integer
            nullable: true
            unsigned: false
        registranteEdicao:
            type: integer
            nullable: true
            unsigned: false
            column: registrante_edicao
        ativo:
            type: boolean
            nullable: true
        portabilidade:
            type: integer
            nullable: true
            unsigned: false
    lifecycleCallbacks: {  }
