Servicos\RhBundle\Entity\RhColaboradorBeneficio:
    type: entity
    table: rh.rh_colaborador_beneficio
    indexes:
        fk_rh_colaborador_beneficio_rh_pessoa1_idx:
            columns:
                - id_colaborador
        fk_rh_colaborador_beneficio_rh_beneficio_tipo1_idx:
            columns:
                - id_beneficio
    id:
        idColaboradorBeneficio:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_colaborador_beneficio
            generator:
                strategy: IDENTITY
    fields:
        idColaborador:
            type: integer
            nullable: false
            unsigned: false
            column: id_colaborador
        idBeneficio:
            type: integer
            nullable: false
            unsigned: false
            column: id_beneficio
        registrante:
            type: integer
            nullable: true
            unsigned: false
        registranteAprovacao:
            type: integer
            nullable: true
            unsigned: false
            column: registrante_aprovacao
        dataAprovacao:
            type: datetime
            nullable: true
            column: data_aprovacao
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        ativo:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
