Servicos\RhBundle\Entity\RhColaboradorFormacao:
    type: entity
    table: rh.rh_colaborador_formacao
    indexes:
        fk_rh_colaborador_formacao_rh_colaborador1_idx:
            columns:
                - id_colaborador
    id:
        idColaboradorFormacao:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_colaborador_formacao
            generator:
                strategy: IDENTITY
    fields:
        idColaborador:
            type: integer
            nullable: false
            unsigned: false
            column: id_colaborador
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        registrante:
            type: integer
            nullable: true
            unsigned: false
        instituicao:
            type: string
            nullable: true
            length: 255
            fixed: false
        escolaridade:
            type: string
            nullable: true
            length: 255
            fixed: false
        curso:
            type: string
            nullable: true
            length: 255
            fixed: false
        dataPrevista:
            type: datetime
            nullable: true
            column: data_prevista
        dataInicial:
            type: datetime
            nullable: true
            column: data_inicial
        dataFinal:
            type: datetime
            nullable: true
            column: data_final
    lifecycleCallbacks: {  }
