Servicos\RhBundle\Entity\RhColaboradorFilial:
    type: entity
    table: rh.rh_colaborador_filial
    indexes:
        fk_rh_colaborador_filial_rh_colaborador1_idx:
            columns:
                - id_colaborador
    id:
        idColaboradorFilial:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_colaborador_filial
            generator:
                strategy: IDENTITY
    fields:
        sistechCodigoid:
            type: integer
            nullable: false
            unsigned: false
            column: sistech_codigoid
        descricao:
            type: string
            nullable: true
            length: 255
            fixed: false
        dataPrevista:
            type: datetime
            nullable: true
            column: data_prevista
        dataInicial:
            type: datetime
            nullable: true
            column: data_inicial
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        dataFim:
            type: datetime
            nullable: true
            column: data_fim
        registrante:
            type: integer
            nullable: true
            unsigned: false
        registranteEdicao:
            type: integer
            nullable: true
            unsigned: false
            column: registrante_edicao
        motivoEdicao:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: motivo_edicao

    manyToOne:
        idColaborador:
            targetEntity: RhColaborador
            cascade: {  }
            mappedBy: null
            inversedBy: colaboradorFilial
            joinColumns:
                id_colaborador:
                    referencedColumnName: id_colaborador
            orphanRemoval: false
    lifecycleCallbacks: {  }
