Servicos\RhBundle\Entity\RhOcorrenciaHorario:
    type: entity
    table: rh.rh_ocorrencia_horario
    indexes:
        fk_rh_ocorrencia_horario_rh_categoria_ocorrencia1_idx:
            columns:
                - id_categoria_ocorrencia
        fk_rh_ocorrencia_horario_documento_gen_idx:
            columns:
                - id_documento_gen
    id:
        idocorrencia:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        horaEntrada:
            type: datetime
            nullable: true
            column: hora_entrada
        intervaloInicio:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: intervalo_inicio
        intervaloFim:
            type: string
            nullable: true
            length: 45
            fixed: false
            column: intervalo_fim
        horaSaida:
            type: datetime
            nullable: true
            column: hora_saida
        matricula:
            type: integer
            nullable: true
            unsigned: false
        registranteLeitura:
            type: integer
            nullable: true
            unsigned: false
            column: registrante_leitura
        observacao:
            type: string
            nullable: true
            length: 255
            fixed: false
        dataLeitura:
            type: datetime
            nullable: true
            column: data_leitura
    manyToOne:
        idDocumentoGen:
            targetEntity: RhDocumentoGen
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_documento_gen:
                    referencedColumnName: id_documento_gen
            orphanRemoval: false
        idCategoriaOcorrencia:
            targetEntity: RhCategoriaOcorrencia
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_categoria_ocorrencia:
                    referencedColumnName: id_categoria_ocorrencia
            orphanRemoval: false
    lifecycleCallbacks: {  }
