Servicos\RhBundle\Entity\RhPerguntaInformativa:
    type: entity
    table: rh.rh_pergunta_informativa
    id:
        idPerguntaInformativa:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_pergunta_informativa
            generator:
                strategy: IDENTITY
    fields:
        pergunta:
            type: string
            nullable: true
            length: 255
            fixed: false
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        ativo:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
