Servicos\RhBundle\Entity\RhPremio:
    type: entity
    table: rh.rh_premio
    indexes:
        fk_rh_premio_rh_colaborador1_idx:
            columns:
                - id_colaborador
    id:
        idPremio:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_premio
            generator:
                strategy: IDENTITY
    fields:
        idColaborador:
            type: integer
            nullable: false
            unsigned: false
            column: id_colaborador
        valor:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        registrante:
            type: integer
            nullable: true
            unsigned: false
        registranteEdicao:
            type: integer
            nullable: true
            unsigned: false
            column: registrante_edicao
        dataInc:
            type: datetime
            nullable: true
            column: data_inc
        dataEdicao:
            type: datetime
            nullable: true
            column: data_edicao
        ativo:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
