BA:
  create:
  - 12
  - 13
  - 14
  - 15
  update:
  - 12
  - 13
  - 14
  - 15
  history:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  read:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  pause:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  restart:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  solve:
  - 12
  - 13
  - 14
  - 15
  unsolved:
  - 12
  - 13
  - 14
  - 15
  comment:
  - 12
  - 13
  - 14
  - 15
  close:
  - 12
  - 13
  - 14
  - 15
  cancel:
  - 15
  send_to_sn2:
  - 12
  - 13
  - 14
  - 15
  send_to_sn3:
  - 12
  - 13
  - 14
  - 15
  change_stack:
  - 12
  - 13
  - 14
  - 15
  send_to_user:
  - 15
  link_to_bi:
  - 12
  - 13
  - 14
  - 15
  take_on:
  - 12
  - 13
  - 14
  - 15
  export_report:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
BI:
  create:
  - 12
  - 13
  - 14
  - 15
  update:
  - 12
  - 13
  - 14
  - 15
  read:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  history:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  take_on:
  - 13
  - 14
  - 15
  send_to_user:
  - 15
  send_to_sn3:
  - 12
  - 13
  - 14
  - 15
  close:
  - 12
  - 13
  - 14
  - 15
  comment:
  - 12
  - 13
  - 14
  - 15
  read_related_ba:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  update_related_ba:
  - 12
  - 13
  - 14
  - 15
  export_report:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
BS:
  create:
  - 12
  - 13
  - 14
  - 15
  read:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  take_on:
  - 12
  - 13
  - 14
  - 15
  send_to_user:
  - 15
  comment:
  - 12
  - 13
  - 14
  - 15
  close:
  - 12
  - 13
  - 14
  - 15
  config:
  - 14
  - 15
SUB_COC:
  close:
  - 15
  - 16
  - 17
  create:
  - 12
  - 13
  - 14
  - 15
  read:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  pause:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  restart:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  update:
  - 15
  - 16
  - 17
SUB_MANTAINER:
  close:
  - 12
  - 13
  - 14
  - 15
  create:
  - 12
  - 13
  - 14
  - 15
  read:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  pause:
  - 12
  - 13
  - 14
  - 15
  restart:
  - 12
  - 13
  - 14
  - 15
  update:
  - 12
  - 13
  - 14
  - 15
