<?php

namespace Servicos\FinanceiroBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DesignacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignacaoRepository extends EntityRepository
{
    public function sttMaxAccess($clieCodigoid,$desigNumero){
        try{
            if($clieCodigoid){
                $query = $this->_em->createQueryBuilder();
                $query->select("Max(desig.desigPonta) as numero")
                    ->from("Servicos\FinanceiroBundle\Entity\Designacao", "desig")
                    ->where("desig.clieCodigoid=".$clieCodigoid." AND desig.desigNumero=".$desigNumero);

                $desig = $query->getQuery()->execute();
                return $desig[0]['numero'];

            }

        }catch(Exception $ex){
            return $ex;
        }
    }

    
    public function sttById($desigCodigoid){
        try{
            if($desigCodigoid && !$desigCodigoid instanceof \Servicos\FinanceiroBundle\Entity\Designacao){
                $desigCodigoid = $this->find($desigCodigoid);
            }
            if($desigCodigoid){
                if($desigCodigoid->getDesigStt()){
                    return 'STT'.$desigCodigoid->getDesigStt().str_pad($desigCodigoid->getDesigNumero(),4,'0',STR_PAD_LEFT);
                }
                else{
                    return 'STT-'.$desigCodigoid->getClieCodigoid().'-'.$desigCodigoid->getDesigNumero().'-'.$desigCodigoid->getDesigPonta();
                }
            }
            
        }catch(Exception $ex){
            return $ex;
        }
    }
}
