<?php

namespace Servicos\FinanceiroBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicoCapacidadeRepository extends EntityRepository
{
    public function getServicoCapacidade(array $filtros = array())
    {
        $query = $this->_em->createQueryBuilder();
        $query->select('sc')
            ->from("ServicosFinanceiroBundle:Servicocapacidade", "sc")
            ->innerJoin("sc.mediCodigoid", "m")
            ->innerJoin("sc.capaCodigoid", "c");

        if (isset($filtros['servico'])) {
            $query->andWhere('sc.servCodigoid = :servico');
            $query->setParameter('servico', $filtros['servico']);
        }

        if (isset($filtros['velocidade'])) {
            $query->andWhere('c.capaCapacidade = :velocidade');
            $query->setParameter('velocidade', $filtros['velocidade']);
        }

        if (isset($filtros['medida_vezes'])) {
            $query->andWhere('m.mediVezes = :medida_vezes');
            $query->setParameter('medida_vezes', $filtros['medida_vezes']);
        }

        if (isset($filtros['medida_categoria'])) {
            $query->andWhere('m.mediCategoria = :medida_categoria');
            $query->setParameter('medida_categoria', $filtros['medida_categoria']);
        }

        if (isset($filtros['medida'])) {
            $query->andWhere('m.mediCodigoid = :medida');
            $query->setParameter('medida', $filtros['medida']);
        }
        
        if (isset($filtros['capacidade'])) {
            $query->andWhere('c.capaCodigoid = :capacidade');
            $query->setParameter('capacidade', $filtros['capacidade']);
        }

        $query->setMaxResults(1);

        return $query->getQuery()->getOneOrNullResult();
    }
}
