Servicos\GcdbBundle\Entity\Accesshistory:
    type: entity
    table: gcdb.AccessHistory
    indexes:
        sid:
            columns:
                - sid
        CustomerID:
            columns:
                - CustomerID
        IP:
            columns:
                - IP
    id:
        sid:
            type: string
            nullable: false
            length: 250
            fixed: false
            default: ''
            id: true
        data:
            type: string
            nullable: false
            length: 30
            fixed: false
            default: ''
            id: true
        customerid:
            type: string
            nullable: false
            length: 10
            fixed: false
            default: ''
            id: true
            column: CustomerID
        ip:
            type: string
            nullable: false
            length: 15
            fixed: false
            default: ''
            id: true
            column: IP
        tipo:
            type: string
            nullable: false
            length: 10
            fixed: false
            default: ''
            id: true
            column: Tipo
    lifecycleCallbacks: {  }
