Servicos\GcdbBundle\Entity\Accounts:
    type: entity
    table: gcdb.Accounts
    indexes:
        AccountID_2:
            columns:
                - AccountID
        CustomerID:
            columns:
                - CustomerID
        Username:
            columns:
                - Username
        ServicoID:
            columns:
                - ServicoID
    uniqueConstraints:
        AccountID:
            columns:
                - AccountID
    id:
        accountid:
            type: integer
            nullable: false
            unsigned: true
            id: true
            column: AccountID
            generator:
                strategy: IDENTITY
    fields:
        customerid:
            type: integer
            nullable: true
            unsigned: true
            column: CustomerID
        username:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: Username
        password:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: Password
        description:
            type: string
            nullable: true
            length: 100
            fixed: false
            column: Description
        dateopened:
            type: date
            nullable: true
            column: DateOpened
        dateclosed:
            type: date
            nullable: true
            column: DateClosed
        price:
            type: float
            nullable: true
            precision: 10
            scale: 2
            column: Price
        status:
            type: string
            nullable: true
            length: 25
            fixed: false
            column: Status
        charged:
            type: string
            nullable: false
            length: 15
            fixed: false
            default: ''
            column: Charged
        servidor:
            type: string
            nullable: true
            length: 100
            fixed: false
            column: Servidor
        plano:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: Plano
        dominio:
            type: string
            nullable: true
            length: 100
            fixed: false
            column: Dominio
        moeda:
            type: string
            nullable: false
            length: null
            fixed: false
            default: R
            column: Moeda
        servicoid:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: ServicoID
        template:
            type: string
            nullable: true
            length: 20
            fixed: false
        accountidOld:
            type: integer
            nullable: false
            unsigned: false
            column: AccountID_Old
        maxPortas:
            type: integer
            nullable: false
            unsigned: false
            column: max_portas
    lifecycleCallbacks: {  }
