Servicos\GcdbBundle\Entity\AdmPais:
    type: entity
    table: gcdb.adm_pais
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sigla:
            type: string
            nullable: true
            length: 3
            fixed: true
        nome:
            type: string
            nullable: true
            length: 30
            fixed: false
        codigoBacen:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: codigo_bacen
    lifecycleCallbacks: {  }
