Servicos\GcdbBundle\Entity\AdmSwitchs:
    type: entity
    table: gcdb.adm_switchs
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ip:
            type: string
            nullable: false
            length: 20
            fixed: false
        nome:
            type: string
            nullable: false
            length: 200
            fixed: false
        qtdPortas:
            type: integer
            nullable: false
            unsigned: false
            column: qtd_portas
        cmdAdmStatus:
            type: string
            nullable: false
            length: 200
            fixed: false
            column: cmd_adm_status
        cmdOpeStatus:
            type: string
            nullable: false
            length: 200
            fixed: false
            column: cmd_ope_status
        cmdTrafficIn:
            type: string
            nullable: false
            length: 200
            fixed: false
            column: cmd_traffic_in
        cmdTrafficOu:
            type: string
            nullable: false
            length: 200
            fixed: false
            column: cmd_traffic_ou
        communittyRead:
            type: string
            nullable: false
            length: 200
            fixed: false
            column: communitty_read
        communittyWrite:
            type: string
            nullable: false
            length: 200
            fixed: false
            column: communitty_write
        cmdNomePort:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: cmd_nome_port
        inversao:
            type: boolean
            nullable: true
            comment: 'Verifica se o Switch é Invertido ou Não 0:Correto  1:Invertido'
        ativo:
            type: boolean
            nullable: false
            comment: 'Verifica se o Switch é ativo ou desativo. 0 - Desativo ou 1 - Ativo'
    lifecycleCallbacks: {  }
