Servicos\GcdbBundle\Entity\AdmTipoTelefone:
    type: entity
    table: gcdb.adm_tipo_telefone
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 20
            fixed: false
    lifecycleCallbacks: {  }
