Servicos\GcdbBundle\Entity\AtividadesPrimarias:
    type: entity
    table: gcdb.atividades_primarias
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 100
            fixed: false
        paiId:
            type: integer
            nullable: false
            unsigned: false
            column: pai_id
        nivel:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        codCnae:
            type: string
            nullable: false
            length: 10
            fixed: false
            column: cod_cnae
    lifecycleCallbacks: {  }
