Servicos\GcdbBundle\Entity\AutPermissoesGrupos:
    type: entity
    table: gcdb.aut_permissoes_grupos
    indexes:
        permissoes_grupos_FKIndex1:
            columns:
                - opcoes_id
        permissoes_grupos_FKIndex2:
            columns:
                - grupos_id
        permissao:
            columns:
                - permissao
    id:
        opcoesId:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            id: true
            column: opcoes_id
        gruposId:
            type: integer
            nullable: false
            unsigned: true
            default: '0'
            id: true
            column: grupos_id
    fields:
        permissao:
            type: integer
            nullable: true
            unsigned: true
    manyToOne:
        autGrupos:
            targetEntity: AutGrupos
            cascade: {  }
            mappedBy: null
            inversedBy: autPermissoesGrupos
            joinColumns:
                grupos_id:
                    referencedColumnName: id
            orphanRemoval: false
        autOpcoes:
            targetEntity: AutOpcoes
            cascade: {  }
            mappedBy: null
            inversedBy: autPermissoesGrupos
            joinColumns:
                opcoes_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
