Servicos\GcdbBundle\Entity\CadLigacaoU2u:
    type: entity
    table: gcdb.cad_ligacao_u2u
    indexes:
        cad_ligacao_u2u_FKIndex1:
            columns:
                - adm_tipo_ligacao_id
        cad_ligacao_u2u_FKIndex2:
            columns:
                - cad_users_id2
        cad_ligacao_u2u_FKIndex3:
            columns:
                - cad_users_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dtInicio:
            type: date
            nullable: true
            column: dt_inicio
        dtFim:
            type: date
            nullable: true
            column: dt_fim
    manyToOne:
        admTipoLigacao:
            targetEntity: AdmTipoLigacao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                adm_tipo_ligacao_id:
                    referencedColumnName: id
            orphanRemoval: false
        cadUsers2:
            targetEntity: CadUsers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cad_users_id2:
                    referencedColumnName: id
            orphanRemoval: false
        cadUsers:
            targetEntity: CadUsers
            cascade: {  }
            mappedBy: null
            inversedBy: cadLigacaoU2u
            joinColumns:
                cad_users_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
