Servicos\GcdbBundle\Entity\Cfop:
    type: entity
    table: gcdb.CFOP
    id:
        cfop:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: CFOP
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
        telecom:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        ufLocal:
            type: integer
            nullable: false
            unsigned: false
            default: '1'
            column: uf_local
    lifecycleCallbacks: {  }
