Servicos\GcdbBundle\Entity\ContrabControl:
    type: entity
    table: gcdb.contrab_control
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tempo:
            type: string
            nullable: false
            length: 100
            fixed: false
        falhaSwitch:
            type: text
            nullable: false
            length: 65535
            fixed: false
            column: falha_switch
        execucao:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
    lifecycleCallbacks: {  }
