Servicos\GcdbBundle\Entity\FornecedoresAprovacao:
    type: entity
    table: gcdb.fornecedores_aprovacao
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        razao:
            type: string
            nullable: true
            length: 200
            fixed: false
        fantasia:
            type: string
            nullable: true
            length: 200
            fixed: false
        ie:
            type: string
            nullable: true
            length: 20
            fixed: false
        im:
            type: string
            nullable: true
            length: 20
            fixed: false
        datafundacao:
            type: date
            nullable: true
        segmento:
            type: integer
            nullable: true
            unsigned: false
        cep:
            type: string
            nullable: true
            length: 10
            fixed: false
        uf:
            type: string
            nullable: true
            length: 2
            fixed: false
        cidade:
            type: string
            nullable: true
            length: 100
            fixed: false
        tipologradouro:
            type: integer
            nullable: true
            unsigned: false
        logradouro:
            type: string
            nullable: true
            length: 200
            fixed: false
        numero:
            type: string
            nullable: true
            length: 20
            fixed: false
        bairro:
            type: string
            nullable: true
            length: 100
            fixed: false
        tipocomplemento:
            type: integer
            nullable: true
            unsigned: false
        complemento:
            type: string
            nullable: true
            length: 200
            fixed: false
        data:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
        cnpj:
            type: string
            nullable: false
            length: 100
            fixed: false
    lifecycleCallbacks: {  }
