Servicos\GcdbBundle\Entity\Origem:
    type: entity
    table: gcdb.Origem
    indexes:
        CustomerID:
            columns:
                - CustomerID
    id:
        origemid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: OrigemID
            generator:
                strategy: IDENTITY
    fields:
        customerid:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
            column: CustomerID
        origem:
            type: string
            nullable: false
            length: 250
            fixed: false
            default: ''
            column: Origem
        agente:
            type: string
            nullable: false
            length: 20
            fixed: false
            default: ''
            column: Agente
        datacadastro:
            type: date
            nullable: false
            default: '0000-00-00'
            column: DataCadastro
    lifecycleCallbacks: {  }
