Servicos\GcdbBundle\Entity\PlanosIp:
    type: entity
    table: gcdb.Planos_IP
    indexes:
        Planos_IP_FKIndex1:
            columns:
                - AccountID
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        accountid:
            type: integer
            nullable: false
            unsigned: false
            column: AccountID
        ip:
            type: string
            nullable: true
            length: 20
            fixed: false
        servidor:
            type: string
            nullable: true
            length: 20
            fixed: false
        tipo:
            type: string
            nullable: true
            length: null
            fixed: false
    lifecycleCallbacks: {  }
