Servicos\GcdbBundle\Entity\SidwebUser:
    type: entity
    table: gcdb.sidweb_user
    indexes:
        CustomerID:
            columns:
                - UserID
        sid:
            columns:
                - sid
    id:
        sid:
            type: string
            nullable: false
            length: 250
            fixed: false
            default: ''
            id: true
        data:
            type: string
            nullable: false
            length: 30
            fixed: false
            default: ''
            id: true
        cpf:
            type: string
            nullable: false
            length: 11
            fixed: false
            id: true
        userid:
            type: string
            nullable: false
            length: 10
            fixed: false
            id: true
            column: UserID
        ip:
            type: string
            nullable: false
            length: 15
            fixed: false
            default: ''
            id: true
            column: IP
    lifecycleCallbacks: {  }
