Servicos\GcdbBundle\Entity\Sidweb:
    type: entity
    table: gcdb.sidweb
    indexes:
        CustomerID:
            columns:
                - CustomerID
        sid:
            columns:
                - sid
    id:
        sid:
            type: string
            nullable: false
            length: 250
            fixed: false
            default: ''
            id: true
        data:
            type: string
            nullable: false
            length: 30
            fixed: false
            default: ''
            id: true
        customerid:
            type: string
            nullable: false
            length: 10
            fixed: false
            default: ''
            id: true
            column: CustomerID
        ip:
            type: string
            nullable: false
            length: 15
            fixed: false
            default: ''
            id: true
            column: IP
    lifecycleCallbacks: {  }
