Servicos\GcdbBundle\Entity\SwitchTemplates:
    type: entity
    table: gcdb.switch_templates
    id:
        idswitchtemplate:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        marca:
            type: string
            nullable: false
            length: 25
            fixed: true
        modelo:
            type: string
            nullable: false
            length: 50
            fixed: true
        url:
            type: string
            nullable: false
            length: 50
            fixed: true
    lifecycleCallbacks: {  }
