Servicos\GcdbBundle\Entity\Switches:
    type: entity
    table: gcdb.Switches
    id:
        switchid:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: SwitchID
            generator:
                strategy: IDENTITY
    fields:
        ip:
            type: string
            nullable: false
            length: 15
            fixed: false
            default: ''
            column: IP
        descricao:
            type: string
            nullable: false
            length: 150
            fixed: false
            default: ''
            column: Descricao
        local:
            type: string
            nullable: false
            length: 150
            fixed: false
            default: ''
            column: Local
        runpath:
            type: string
            nullable: false
            length: 250
            fixed: false
            default: ''
            column: RunPath
    lifecycleCallbacks: {  }
