Servicos\GcdbBundle\Entity\TdmEnlaceSide:
    type: entity
    table: gcdb.tdm_enlace_side
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descricao:
            type: string
            nullable: false
            length: 255
            fixed: false
        capacidadeSdhPdh:
            type: string
            nullable: false
            length: 20
            fixed: false
            column: capacidade_sdh-pdh
    lifecycleCallbacks: {  }
