Servicos\GcdbBundle\Entity\TempCadUsersTelefone:
    type: entity
    table: gcdb.temp_cad_users_telefone
    indexes:
        cad_users_telefones_FKIndex1:
            columns:
                - adm_tipos_telefone_id
        cad_users_telefones_FKIndex2:
            columns:
                - cad_users_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cadUsersId:
            type: integer
            nullable: true
            unsigned: true
            column: cad_users_id
        admTiposTelefoneId:
            type: integer
            nullable: true
            unsigned: false
            column: adm_tipos_telefone_id
        ddi:
            type: integer
            nullable: true
            unsigned: true
        ddd:
            type: string
            nullable: true
            length: 30
            fixed: false
        telefone:
            type: string
            nullable: true
            length: 30
            fixed: false
        ramal:
            type: integer
            nullable: true
            unsigned: false
        principal:
            type: boolean
            nullable: true
        emergencia:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
