Servicos\GcdbBundle\Entity\TempCadLigacaoU2u:
    type: entity
    table: gcdb.temp_cad_ligacao_u2u
    indexes:
        cad_ligacao_u2u_FKIndex1:
            columns:
                - adm_tipo_ligacao_id
        cad_ligacao_u2u_FKIndex2:
            columns:
                - cad_users_id2
        cad_ligacao_u2u_FKIndex3:
            columns:
                - cad_users_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cadUsersId:
            type: integer
            nullable: true
            unsigned: true
            column: cad_users_id
        cadUsersId2:
            type: integer
            nullable: true
            unsigned: true
            column: cad_users_id2
        admTipoLigacaoId:
            type: integer
            nullable: true
            unsigned: false
            column: adm_tipo_ligacao_id
        dtInicio:
            type: date
            nullable: true
            column: dt_inicio
        dtFim:
            type: date
            nullable: true
            default: '0000-00-00'
            column: dt_fim
        temp:
            type: string
            nullable: false
            length: 4
            fixed: false
    lifecycleCallbacks: {  }
