Servicos\GcdbBundle\Entity\VinculosAprovacao:
    type: entity
    table: gcdb.vinculos_aprovacao
    indexes:
        id_fornecedor:
            columns:
                - id_fornecedor
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idCategoria:
            type: integer
            nullable: true
            unsigned: false
            column: id_categoria
        idProduto:
            type: integer
            nullable: true
            unsigned: false
            column: id_produto
    manyToOne:
        idFornecedor:
            targetEntity: FornecedoresAprovacao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_fornecedor:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
